### All tasks are commented out, only uncomment necessary tasks to run. ###
#
### Syntax to run: ansible-playbook -i <inventory> config.yml

# Deploy OpenShift
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

# A la carte playbooks to reconfigure infrastructure and install additional components
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-etcd/config.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-master/config.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-master/additional_config.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-hosted/config.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-web-console/config.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-node/bootstrap.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-monitoring/config.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-metrics/config.yml
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml

# Uninstall OpenShift
# - import_playbook: /usr/share/ansible/openshift-ansible/playbooks/adhoc/uninstall.yml
