---
- name: "add wildcard to dnsmasq config on nodes"
  hosts: ocp
  tasks:
    - name: 'template for the config file'
      notify: 'restart dnsmasq'
      template: 
        src: 'dnsmasq-wildcard.conf.j2'
        dest: '/etc/dnsmasq.d/dnsmasq-wildcard.conf'
        mode: 644
        state: present

  handlers:
    - name: 'restart dnsmasq'
      service: 
        name: dnsmasq
        state: restarted
