# Connect to nodes as root user.
ansible_ssh_user: root

# Set deployment type to deploy enterprise as opposed to origin or a stand-alone registry
openshift_deployment_type: openshift-enterprise

# Disable memory check for small home labs
openshift_disable_check: memory_availability

# Red Hat recommends firewalld instead of iptables
os_firewall_use_firewalld: true

# Master configurations
openshift_master_cluster_method: native

# Install OpenShift templates and service catalog by default
openshift_install_examples: true
openshift_enable_service_catalog: true
