# Install metrics
openshift_metrics_install_metrics: true
openshift_metrics_cassandra_nodeselector: {"node-role.kubernetes.io/infra":"true"}
openshift_metrics_hawkular_nodeselector: {"node-role.kubernetes.io/infra":"true"}
openshift_metrics_heapster_nodeselector: {"node-role.kubernetes.io/infra":"true"}

# Optional tuning for small home labs
openshift_metrics_cassandra_limits_memory: 2G
openshift_metrics_cassandra_requests_memory: 500m
openshift_metrics_hawkular_limits_memory: 2G
openshift_metrics_hawkular_requests_memory: 500m
openshift_metrics_heapster_limits_memory: 2G
openshift_metrics_heapster_requests_memory: 500m
