# https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/installing_clusters/install-config-configuring-inventory-file
openshift_node_groups:
  - name: node-config-master
    labels:
      - 'node-role.kubernetes.io/master=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-infra
    labels:
      - 'node-role.kubernetes.io/infra=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-compute
    labels:
      - 'node-role.kubernetes.io/compute=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-master-infra
    labels:
      - 'node-role.kubernetes.io/infra=true,node-role.kubernetes.io/master=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-all-in-one
    labels:
      - 'node-role.kubernetes.io/infra=true,node-role.kubernetes.io/master=true,node-role.kubernetes.io/compute=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-master-crio
    labels:
      - 'node-role.kubernetes.io/master=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-infra-crio
    labels:
      - 'node-role.kubernetes.io/infra=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-compute-crio
    labels:
      - 'node-role.kubernetes.io/compute=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-master-infra-crio
    labels:
      - 'node-role.kubernetes.io/infra=true,node-role.kubernetes.io/master=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
  - name: node-config-all-in-one-crio
    labels:
      - 'node-role.kubernetes.io/infra=true,node-role.kubernetes.io/master=true,node-role.kubernetes.io/compute=true'
    edits:
      - key: kubeletArguments.image-gc-high-threshold
        value:
          - "80"
      - key: kubeletArguments.image-gc-low-threshold
        value:
          - "70"
